# Generated by Django 5.1.6 on 2025-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("symbol", models.CharField(max_length=200, null=True)),
                ("image_url", models.URLField(null=True)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=50, null=True),
                ),
                (
                    "price_change_within_24_hours",
                    models.DecimalField(decimal_places=2, max_digits=50, null=True),
                ),
                ("rank", models.IntegerField(null=True)),
                (
                    "market_cap",
                    models.DecimalField(decimal_places=2, max_digits=50, null=True),
                ),
                (
                    "total_supply",
                    models.DecimalField(decimal_places=2, max_digits=50, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Coins",
            },
        ),
        migrations.CreateModel(
            name="FullCoin",
            fields=[
                (
                    "coin_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "current_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("market_cap_rank", models.IntegerField(blank=True, null=True)),
                (
                    "fully_diluted_valuation",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "high_24h",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "low_24h",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "price_change_percentage_24h",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
                ),
                (
                    "market_cap_change_24h",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "market_cap_change_percentage_24h",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
                ),
                (
                    "circulating_supply",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "total_supply",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "max_supply",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "ath",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "ath_change_percentage",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
                ),
                ("ath_date", models.DateTimeField(blank=True, null=True)),
                (
                    "atl",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "atl_change_percentage",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
                ),
                ("atl_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
