# Generated by Django 4.0.4 on 2022-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('symbol', models.CharField(max_length=200, null=True)),
                ('image_url', models.URLField(null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('price_change_within_24_hours', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
            ],
        ),
    ]
